DROP TABLE TASK_TASK_LIST_ASSIGNMENT;
DROP TABLE TASK;
DROP TABLE TAG;
DROP TABLE TASK_LIST;
DROP TABLE USER;

CREATE TABLE USER
(
    USERNAME VARCHAR(15),
    EMAIL    VARCHAR(45),
    PASSWORD VARCHAR(45),
    CONSTRAINT PK_USER PRIMARY KEY (EMAIL)
);


CREATE TABLE TASK_LIST
(
    ID      INT AUTO_INCREMENT,
    NAME    VARCHAR(15),
    USER_ID VARCHAR(45),
    CONSTRAINT PK_TASK_LIST PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_LIST_USER FOREIGN KEY (USER_ID)
        REFERENCES USER (EMAIL)
);



CREATE TABLE TAG
(
    ID           INT AUTO_INCREMENT,
    NAME         VARCHAR(15),
    TASK_LIST_ID INT,
    CONSTRAINT PK_TAG PRIMARY KEY (ID),
    CONSTRAINT FK_TAG_TASK_LIST FOREIGN KEY (TASK_LIST_ID)
        REFERENCES TASK_LIST (ID)
);

CREATE TABLE TASK
(
    ID           INT AUTO_INCREMENT,
    DUE_DATE     DATETIME,
    NAME         VARCHAR(15),
    DESCRIPTION  VARCHAR(200),
    IS_DONE      BOOLEAN,
    TASK_LIST_ID INT,
    CONSTRAINT PK_TASK PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_TASK_LIST FOREIGN KEY (ID)
        REFERENCES TASK_LIST (ID)
);

CREATE TABLE TASK_TASK_LIST_ASSIGNMENT
(
    TASK_LIST_ID INT,
    TASK_ID      INT,
    CONSTRAINT PK_TASK_TASK_LIST_ASSIGNMENT
        PRIMARY KEY (TASK_ID, TASK_LIST_ID),
    CONSTRAINT FK_TASK_TASK_LIST_ASSIGNMENT_TASK_LIST
        FOREIGN KEY (TASK_LIST_ID)
            REFERENCES TASK_LIST (ID),
    CONSTRAINT FK_TASK_TASK_LIST_ASSIGNMENT_TASK
        FOREIGN KEY (TASK_ID)
            REFERENCES TASK (ID)
);

